### ISSUE TITLE
Meeting #2 👨‍💻

### ISSUE THREAD

**Issue by JonasVanhulst** [JonasVanhulst/IOT_Dashboard#12]
- Github
- PYNQ
-

**Comment by JonasVanhulst** [comment]
Is it possible to meet up tomorrow in the morning or evening. We need to discuss some points about the tasks.

**Comment by JasperMaes01** [comment]
I add my code for the About Us page. We can start from there on. By sunday, I can be ready with this page, as I can work on it this weekend. 
Can you please list our to-do for this page?

**Comment by JonasVanhulst** [comment]
Ok, today i will update the timeline what needs to be done and i will push the about page what i made.
