### ISSUE TITLE
Meeting #3

### ISSUE THREAD

**Issue by JonasVanhulst** [JonasVanhulst/IOT_Dashboard#24]

**Comment by JonasVanhulst** [comment]
So, i have created a data graph for the website, a database demo for testing restful api with get, post and delete. Can you pls check, we need to start writing the api so we can finish the back-end.

Bryan has started up the new server. I connected with it and we need to change the password so we have no insecured connections.

**Comment by JasperMaes01** [comment]
I'll take a look at the code. I'm working on the setup of the Pynq board, so we can use real data in the future.

**Comment by JonasVanhulst** [comment]
If the pynq is working we only need to find a way to set an easy RESTFUL API for get,post,connect and delete into the database (postgreSQL)

**Comment by JonasVanhulst** [comment]
Bryan said that he would publish a video for installing the board. But maybe if you can fix it we doen't need to wait for the solution
