### ISSUE TITLE
Edit path's to new folder structure

### ISSUE THREAD

**Issue by JasperMaes01** [JonasVanhulst/IOT_Dashboard#29]
We will need to edith all path's refering to the images and DATA folder, as these are replaced.

**Comment by JonasVanhulst** [comment]
yes, i did this on the train. Your changes won't work because you forget the root, i will push my changes into the main.

**Comment by JasperMaes01** [comment]
The folder doesn't need to be called root, 'sources' should also do, as long as it is set up right. All though it's cleaner to use root.

**Comment by JasperMaes01** [comment]
Fixed in #30
